USE bsmith257_my_guitar_shop1;
#USE campgeiger2019;
INSERT INTO Geiger2019 (ActivityName, Location, ActivityTime, ActivityLength, RecommendedFor, Materials, Costs, PreReq)
VALUES
  ('Animal Science MB', 
  'Nature Lodge', 
  '11 A.M. / 4 P.M.', 
  '1 Hour', 
  'Any Scout', 
  'Paper and Pencil or Pen, Water Bottle', 
  'NONE', 
  'NONE'),
  ('Archaeology BM', 
  'Nature Lodge', 
  '10 A.M. / 2 P.M.', 
  '1 Hour', 
  'Any Scout', 
  'Paper and Pencil or Pen, Water Bottle', 
  'NONE', 
  'NONE'),
  ('Archery MB', 
  'Archery Range', 
  '9 A.M. / 11 A.M. / 3 P.M. / 4 P.M.',
  '1 Hour', 
  '3rd year camper or 13 years of age or older', 
  'Arrow Kit, which are available at the Trading Post',
  '$5.00', 
  'NONE'),
  ('Astronomy MB', 
  'Nature Lodge', 
  '9 A.M.', 
  '1 Hour', 
  'Scouts who have completed the 7th grade', 
  'Paper and pen or pencil', 
  'NONE', 
  'NONE'),
  ('Automotive Maintenance MB', 
  'Handcraft Corral', 
  '9 A.M. / 10 A.M. / 2 P.M.', 
  '1 Hour', 
  'Any Scout', 
  'Paper and pen or pencil', 
  'NONE', 
  'NONE'),
  ('Basketry and Textile MB', 
  'Handicraft Pavilion', 
  '10 A.M. / 11 A.M. / 2 P.M. / 3 P.M. / 4 P.M.', 
  '1 Hour', 
  'Any Scout', 
  'Basketry materials, which are available at the Trading Post', 
  '10 dollars', 
  'NONE'),
  ('Bird Study MB', 
  'Nature Lodge', 
  '10 A.M.', 
  '1 Hour', 
  'Any Scout', 
  'Binoculars are highly recommended. Paper and pen or pencil', 
  'NONE',
  'NONE'),
  ('Camping MB', 
  'Scoutcraft Pavilion', 
  '2 P.M. / 3 P.M.', 
  '1 Hour', 
  '2nd year camper and older, preferably First Class rank or higher', 
  'NONE', 
  'NONE', 
  'NONE'),
  ('Canoeing MB', 
  'Lake Front', 
  '9 A.M.', 
  '2 Hours', 
  '3rd year camper or 13 years of age and older', 
  'Shoes that can get wet', 
  'NONE', 
  'The Scout must attain Swimmer classification during the Sunday swim check. Participants need to be ready to get wet every day.'),
  ('Chess MB', 
  'Trading Post', 
  '11 A.M. / 2 P.M.', 
  '1 Hour', 
  'Any Scout', 
  'NONE', 
  'NONE', 
  'NONE'),
  ('Citizenship in the Community MB', 
  'Eagle training area (Handicraft Bldg.)', 
  '9 A.M. / 2 P.M.', 
  '1 Hour', 
  '2nd year camper or older and preferably First Class', 
  'Paper and pen or pencil', 
  'NONE', 
  'Visit to a public meeting and community service requirements cannot be completed at camp.  Scouts who attend a public meeting before camp should bring a copy of the agenda and be prepared to discuss the meeting. A written note from the Scoutmaster certifying completion of the community service will be accepted.'),
  ('Citizenship in the Nation MB', 
  'Eagle training area (Handicraft Bldg.)', 
  '10 A.M. / 3 P.M.',
  '1 Hour', 
  '2nd year camper or older and preferably First Class', 
  'Paper and pen or pencil', 
  'NONE', 
  'Review the requirements and bring a note from a parent or Scoutmaster certifying completion of the site visits. As time allows, the letter to a Congressman or Senator may be completed at camp.'),
  ('Citizenship in the World MB', 
  'Eagle training area (Handicraft Bldg.)',
  '11 A.M. / 3 P.M.', 
  '1 Hour', 
  '2nd year camper or older and preferably First Class', 
  'Paper and pen or pencil', 
  'NONE',
  'NONE'),
  ('Climbing MB', 
  'Climbing Tower',
  '9 A.M.',
  '2 Hours',
  'Any Scout',
  'Closed toe shoes',
  'NONE',
  'No fear of heights.'),
  ('Communication MB', 
  'Eagle training area (Handicraft Bldg.)',
  '9 A.M. / 2 P.M.',
  '1 Hour',
  '2nd year camper or older and preferably First Class', 
  'Paper and pen or pencil', 
  'NONE',
  'Scouts who attend a public meeting before camp should bring a copy of the agenda and be prepared to discuss the meeting.'),
  ('Cooking MB',
  'Sol Hirsh Lodge in Handicraft Corral',
  '9 A.M. / 2 P.M.',
  '2 Hours',
  'Any Scout',
  'NONE',
  'NONE',
  'Requirement 5 cannot be completed at camp. A Scout may bring a note signed by his Scoutmaster indicating the meal requirements have been completed.'),
  ('Cycling MB',
  'Cycling shed (near Trading Post)',
  '9 A.M. / 10 A.M. / 11 A.M. / 2 P.M. / 3 P.M.', 
  '1 Hour',
  '3rd year camper or 13 years of age or older',
  'Personal First Aid Kit, Closed toe shoes, Water bottle', 
  'NONE', 
  'NONE'),
  ('Electricty MB',
  'Basement of Maryville Lodge', 
  '9 A.M. / 2 P.M.', 
  '1 Hour', 
  'Any Scout', 
  'Paper and pen or pencil, water bottle',
  'NONE',
  'Scouts should wear long pants'),
  ('Emergency Preparedness MB',
 'Sol Hirsh Lodge in Handicraft Corral',
 '11 A.M. / 3 P.M.',
 '1 Hour',
 '2nd year camper or older',
 'Emergency Kit', 
 'NONE', 
 'First Aid Merit Badge is required and may be taken in the same camp session. Scouts will need to complete the emergency kit before coming to camp.'),
  ('Environmental Science MB',
   'Nature Lodge',
   '9 A.M. / 3 P.M.',
   '2 Hours',
   'Any Scout',
   'Paper and pen or pencil',
   'NONE',
   'Part of this activity requires a nature hike. Wear appropriate closed-toe shoes and bring a water bottle every day of the activity.'),
   ('Fingerprinting & Crime Prevention', 
   'Basement of Goetz Lodge',
   '2 P.M. / 3 P.M. / 4 P.M.',
   '1 Hour',
   'Any Scout',
   'Paper, pen or pencil', 
   'NONE', 
   'The Crime Prevention notebook requirement cannot be completed at camp. A Scout may prepare and bring a notebook of newspaper and other clippings that address crime and crime prevention efforts in his community to meet this requirement.'),
   ('First Aid MB', 
   'Sol Hirsh Lodge in Handicraft Corral', 
   '10 a.m. / 2 p.m.',
   '1 Hour',
   '2nd year camper and older',
   'Scout-built personal First Aid kit', 
   'NONE',
   'If a Scout wishes to complete the badge at camp, he must bring the personal First Aid kit he built prior to camp.'),
   ('Fish and Wildlife & Forestry MB', 
   'Nature Lodge', 
   '11 a.m. / 2 p.m.',
   '1 hour', 'Any Scout',
   'Paper, pen or pencil', 
   'NONE',
   'NONE'), 
   ('Fishing MB',
   'Lake Front',
   '9 a.m. period but starts at 8:30 a.m.',
   '1 hour 30 minutes', 
   'Any Scout', 
   'All fishing gear will be provided', 
   'NONE', 
   'NONE'), 
   ('Fly Fishing MB', 
   'Lake Front', 
   '4 p.m.',
   '1 hour',
   '3rd year campers or 13 years of age and older',
   'NONE',
   '$5.00',
   'NONE'), 
   ('Geology & Soil and Water Conservation MB', 
   'Nature Lodge',
   '11 a.m. / 4 p.m.',
   '1 hour',
   'Any Scout',
   'Paper, pen or pencil, closed-toe shoes',
   'NONE',
   'This activity does require a nature hike and a conservation project. Please wear closed-toe shoes and bring a water bottle every day.'),
   ('Golf MB', 
   'Scoutcraft Pavilion',
   '10 a.m. / 11 a.m.', 
   '1 hour',
   '2nd year camper and older', 
   'Water bottle', 
   'NONE',
   'Requirements involving completing rounds of golf cannot be completed at camp. A Scout can bring a written note from the Scoutmaster or a scorecard from the course to show proof of completion.'),
   ('Indian Lore', 
   'Tipi near Goetz, Swimming Rock Lodges', 
   '10 a.m. / 11 a.m. / 3 p.m. / 4 p.m.',
   '1 hour',
   '2nd year camper and older', 
   'Costume kits, which are available at the Trading Post', 
   'Approximately $20.00', 
   'NONE'),
   ('Kayaking MB',
   'Lake Front', 
   '10 a.m. / 2 p.m.', 
   '2 hours', 
   'Any Scout',
   'Shoes that can get wet.',
   'NONE',
   'The Scout must attain “Swimmer” classification during the Sunday swim check. Participants should plan on being in the water every day and should wear appropriate clothing.'),
   ('Leatherwork MB', 
   'Handicraft Pavilion', 
   '9 a.m. / 11 a.m. / 2 p.m. / 3 p.m. / 4 p.m.',
   '1 hour',
   'Any Scout',
   'Leatherworking kits can be purchased at the Trading Post',
   '$15.00',
   'NONE'),
   ('Lifesaving MB', 
   'Pool', 
   '9 a.m.', 
   '2 hours', 
   '3rd year camper or 13 years of age or older', 
   'Long-sleeved buttoned shirt, long pants, belt, shoes, socks, swim trunks, towel', 
   'NONE', 
   'Scout must have earned Swimming Merit Badge. A 440-yard qualifying swim will be required the first day of the activity, Only strong swimmers will be able to qualify for this badge. Completion of CPR course prior to camp is recommended. There will be CPR training on Thursday night at 5 p.m., but it can be replaced with a CPR training card or other documentation.'),
   ('Metalwork MB', 
   'Handicraft Pavilion', 
   '9 a.m./10 a.m./11 a.m./3 p.m./4 p.m.', 
   '1 hour',
   '16 years of age and older', 
   'Jeans or thick cloth pants, closed toe shoes, no nylon or polyester shirts', 
   '$13.00', 
   'NONE'),
   ('Music MB', 
  'Trading Post', 
  '9 a.m. / 10 a.m.',
  '1 hour', 'Any Scout',
  'NONE', 
  'NONE', 
  'NONE'),
   ('Oceanography & Weather',
   'Nature Lodge', 
   '9 a.m. / 4 p.m.',
   '1 hour',
   'Any Scout', 
   'Paper, pen or pencil', 
   'NONE',
   'NONE'),
   ('Orienteering MB',
   'Scoutcraft Pavilion', 
   '3 p.m.', 
   '1 hour', 
   'Any Scout', 
   'Compass, hiking boots or shoes, water bottle', 
   'NONE', 
   'NONE'),
   ('Personal Fitness MB', 
   'Sol Hirsh Lodge in Handicraft Corral', 
   '9 a.m./11 a.m./4 p.m.', 
   '1 hour', 
   '2nd year camper or older, preferably First Class or above', 
   'Tennis shoes, paper, pen or pencil', 
   'NONE', 
   'NONE'),	
    ('Personal Management MB',
    'Sol Hirsh Lodge in Handicraft Corral',
    '10 a.m./2 p.m./3 p.m.',
    '1 hour',
    '2nd year camper or older, preferably First Class or above',
    'Paper, pen or pencil',
    'NONE',
    'NONE'),
    ('Photography MB',
    'Museum',
    '9 a.m./3 p.m.',
    '1 hour',
    '2nd year camper and older',
    'Sturdy shoes and a water bottle',
    'NONE',
	'Scouts must earn their Cyber Chip prior to camp and bring documentation to camp. Scouts may bring their own camera but will need to use a provided SD memory card. A cell phone with a camera does not work. A flash drive is needed to take home any pictures taken on camp devices. Pictures taken may be used for the weekly slide show. Scouts will hike to various areas on camp to take photos.'),
	('Pottery and Sculpture MB',
    'Handicraft Pavilion',
    '9 a.m. / 10 a.m. / 2 p.m. / 3 p.m. / 4 p.m.',
    '1 hour',
    'Any Scout',
    'Paper, Pen or Pencil',
    '$5.00',
    'NONE'),    
    ('Plumbing MB',
    'Basement of Maryville Lodge',
    '3 p.m. / 4 p.m.',
    '1 hour',
    'Any Scout',
    'Paper and pen or pencil, water bottle',
    'NONE',
    'Scouts should wear long pants.'),
    ('Radio MB',
    'Front porch of Goetz Lodge',
    '10 a.m. / 11 a.m.',
    '1 hour',
    'Any Scout',
    'Paper, pen or pencil',
    'NONE',
    'NONE'),    
    ('Rifle Shooting (.22 cal) MB',
    'Rifle Range',
    '9 a.m./10 a.m./11 a.m./2 p.m./3 p.m.',
    '1 hour',
    'Any Scout',
    'NONE',
    '$7.50',
    'NONE'),    
    ('Reptile & Amphibian Study MB',
    'Nature Lodge',
    '9 a.m. / 2 p.m.',
    '1 hour',
    'Any Scout',
    'Paper, pen or pencil',
    'NONE',
    'NONE'),
    ('Rowing',
    'Lake Front',
    '2 p.m.',
    '2 hours',
    '3rd year campers or 13 years of age or older',
    'Shoes that can get wet',
    'NONE',
    'NONE'),
    ('Search and Rescue MB',
    'Scoutcraft Pavilion',
    '2 p.m. / 3 p.m. / 4 p.m',
    '1 hours',
    '2nd year or older',
    'NONE',
    'NONE',
    'NONE'),
    ('Shotgun Shooting MB',
    'Shotgun Range',
    '9 a.m. / 10 a.m. / 11 a.m./ 2 p.m./ 4 p.m.',
    '1 hour',
    'Must be 3rd year camper or 13 years of age or older',
    'NONE',
    '$15.00',
    'NONE'),
    ('Space Exploration MB',
    'Nature Lodge',
    '2 p.m. / 3 p.m.',
    '1 hour',
    'Any Scout',
    'Estes Viking model rocket kit',
    '$15.00',
    'NONE'),
    ('Sustainability MB',
    'Nature Lodge',
    '10 a.m./3 p.m.',
    '1 hour',
    '2nd year camper or older',
    'Paper, pen or pencil',
    'NONE',
    'NONE'),
    ('Swimming MB',
    'Pool',
    '10 a.m. / 2 p.m.',
    '2 hours',
    'Any Scout',
    'Swim trunks and towel',
    'NONE',
    'The Scout must attain “Swimmer” classification during the Sunday swim check.'),
    ('Wilderness Survival MB',
    'Scoutcraft Pavilion',
    '4 p.m.',
    '1 hour',
    '2nd year camper or older',
    'Sleeping bag, clothing suitable to spend the night in the open, pocket knife, survival kit.',
    'NONE',
    'NONE'),
    ('Woodcarving MB',
    'Handicraft Pavilion',
    '9 a.m./10 a.m./11 a.m./3 p.m./4 p.m.',
    '1 hour',
    '2nd year camper or older',
    'Leather gloves are furnished but Scout may bring his own.',
    '$5.00',
    'Scouts should not bring their own knives to the activity. A totin/ chip must be shown to be allowed to use the
tools provided. * The activity fee will be added to the Scout’s camp registration fees, and the materials will be
provided to the Scout during the activity period.'),
    ('Beginning Swimmer’s',
    'Pool',
    '3 p.m. / 4 p.m.',
    '1 hour',
    'Beginner level swimmers',
    'Swim trunks and towel',
    'NONE',
    'The Scout must attain “Beginner” classification during the Sunday swim check. This activity is designed for
Scouts to learn and practice strokes with the goal of advancing to “Swimmer” level.'),
    ('COPE',
    'Climbing Tower',
    '9 a.m.',
    '3 hours',
    '3rd year camper or 13 years and older',
    'Closed toe shoes and clothing that can get dirty',
    'None',
    'Scouts must be present and participate every day to earn the COPE shirt. Scouts must be mature enough to
handle the safety of others around them.'),
    ('ELITE',
    'Varies (schedule given at check-in)',
    '3 p.m.',
    '2 hours',
    '14 years of age and older and at least a Life Scout, preferably an Eagle Scout',
    'NONE',
    '$10.00',
    'NONE'),
    ('Extra Swimming / Lifesaving',
    'Pool',
    '11 a.m.',
    '1 hour',
    'Scouts needing to complete Swimming or Lifesaving requirements',
    'Swim trunks and towel',
    'NONE',
    'NONE'),
    ('First Class Trail',
    'Scoutcraft Pavilion',
    '9 a.m.',
    '3 hours',
    'Scout Rank or Tenderfoot Rank Scouts',
    'Sturdy shoes, water bottle, swimming trunks and towel',
    'NONE',
    'NONE'),
    ('Johnny Fry',
    'Cowboy Action Range (initially)',
    '3:00 p.m.',
    '2 hours',
    '2nd year camper or older',
    'Dressing up in Western style is encouraged. ',
    '$10.00',
    'NONE'),
    ('Leave No Trace',
    'Nature Lodge',
    '10 a.m.',
    '1 hour',
    '2nd year camper or older, any adult leader',
    'Paper and pen or pencil, Boy Scout Handbook, water bottle',
    'NONE',
    'NONE'),
    ('Mic-O-Say',
    'Council Ring',
    '1:30 or 2:00',
    '1 1/2 hours',
    'All Braves, Hardway Warriors, and Tom-Tom Beaters',
    'Current costume for Mic-O-Say rank when directed to bring it.',
    'NONE',
    'NONE'),
    ('Mile Swim',
    'Pool',
    'M-T-W 6 a.m',
    '1 hour',
    'Any Scout of Leader who is a proficient swimmer',
    'Swim trunks and towe',
    'NONE',
    'The Scout or Leader must attain “Swimmer” classification during the Sunday swim check.'),
    ('Non-Swimmer',
    'Pool',
    '3 p.m. / 4 p.m.',
    '1 hour',
    'Non-swimmers',
    'Swim trunks and towel',
    'NONE',
    'NONE'),
    ('Paddle Craft Safety Training',
    'Lake Front',
    'Arranged',
    '3 hours',
    '15 years of age and older',
    'Shoes and clothing that can get wet',
    'NONE',
    'The Scout must attain “Swimmer” classification during the Sunday swim check.'),
    ('Swimming and Water Rescue Training',
    'Pool',
    'Arranged',
    '2 hours',
    '16 years and older',
    'Swim trunks and towel',
    'NONE',
    'The Scout must attain “Swimmer” classification during the Sunday swim check.');

